parameters:
    database_host: localhost
    database_port: null
    database_name: hcv1_db
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 4673793c16d4e46310eb28c64ce0a4c08
    database_driver: pdo_mysql
    database_path: null
